---
- name: Detect OS platform
  setup:
    filter: ansible_os_family
  register: os_facts

- name: Display OS information
  debug:
    msg: "Operating System: {{ os_facts.ansible_facts.ansible_os_family }}"

- name: Set Windows variables
  set_fact:
    instana_config_path: "C:\\Program Files\\Instana\\Agent"
    instana_config_dir: "{{ instana_config_path }}\\etc\\instana"
    service_name: "InstanaAgent"
    instana_backup_dir: "C:\\Instana\\Backup"
  when: os_facts.ansible_facts.ansible_os_family == "Windows"

- name: Set Linux variables
  set_fact:
    instana_config_path: "/opt/instana/agent"
    instana_config_dir: "{{ instana_config_path }}/etc/instana"
    service_name: "instana-agent"
    instana_backup_dir: "/opt/instana/backup"
  when: os_facts.ansible_facts.ansible_os_family != "Windows"

- name: Display configuration paths
  debug:
    msg: |
      Instana config path: {{ instana_config_path }}
      Config directory: {{ instana_config_dir }}
      Service name: {{ service_name }}
      Backup directory: {{ instana_backup_dir }}