# Look for these patterns and fix them:

# Fix conditionals - always quote when statements
when: "os_facts.ansible_facts.ansible_os_family == 'Windows'"

# Fix complex when conditions - use YAML block syntax or quotes
when: >
  saas_config is defined and
  saas_config.com is defined and
  saas_config.com.instana is defined and
  saas_config.com.instana.agent is defined and
  saas_config.com.instana.agent.backend is defined

# OR use list format for complex conditions
when:
  - saas_config is defined
  - saas_config.com is defined
  - saas_config.com.instana is defined
  - saas_config.com.instana.agent is defined
  - saas_config.com.instana.agent.backend is defined

# Fix Windows paths - ensure double backslashes
dest: "{{ instana_config_dir }}\\{{ config_file_name | replace('.yaml', '.onprem.yaml') | replace('.yml', '.onprem.yml') }}"

# Fix Linux paths - use forward slashes
dest: "{{ instana_config_dir }}/{{ config_file_name | replace('.yaml', '.onprem.yaml') | replace('.yml', '.onprem.yml') }}"