---
dependency:
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance
    image: "geerlingguy/docker-ubuntu2004-ansible:latest"