---
- name: Remove on-prem config and use SaaS only
  hosts: instana_agents
  vars_files:
    - vars/instana-vars.yml
  collections:
    - instana_migration.collection

  roles:
    - instana_saas_only